### ISSUE TITLE
Camera Movement 

### ISSUE THREAD

**Issue by foxracinggurl** [davitz/heisenberg#27]
We need to set up the camera so that it follows the player.

**Comment by foxracinggurl** [comment]
Jess is confused. 

Talk about stationary camera with the whole level seen. 
For larger levels everything will be smaller within the level (character, items ect) so that we can get everything on screen.

**Comment by Niktib** [comment]
Looking at how big of a screen will be and just seeing how much design space we have without it getting hard to see the player, I think for now we will stick with the stationary camera and if problems do occur, we can look into the camera following the player.

Other thing to keep in mind is that I know unity has a setting to follow the player, so it won't be hard to change if we do need to
